<!doctype html public "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title><?echo$sitename?></title>
<meta name="resource-type" content="document">
<meta name="revisit-after" content="5">
<meta name="description" content="<?echo$description?>">
<meta name="robots" content="ALL">
<meta name="distribution" content="Global">
<meta name="copyright" content="© 2005-2006 TheScripters.com">
<meta name="author" content="TheScripters">
<meta http-equiv="reply-to" content="<?echo$webmasterEM?>">
<link title="RSS" rel="alternate" type="application/rss+xml" href="http://<?echo$site?>/rss.php">
<link rel="stylesheet" href="includes/ffp.css" type="text/css">
</head>

<body>
<h1><?echo$sitename?></h1>
